name: "Update release tags"

on:
  # Triggered manually or via Air's release process
  workflow_dispatch:

jobs:
  tag:
    name: Update release tags
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - if: ${{ startsWith(github.event_name, 'repository_dispatch') }}
        run: sleep 30

      - uses: actions/checkout@v4
        with:
          # Needed to push commits below
          persist-credentials: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run mirror
      - run: uv run --no-project mirror.py

      - name: Check for unpushed commits
        run: |
          UNPUSHED_COMMITS=$(git log origin/main..HEAD)
          if [ -z "$UNPUSHED_COMMITS" ]; then
            echo "No unpushed commits found."
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "Unpushed commits found."
            echo "changes_exist=true" >> $GITHUB_ENV
          fi

      - name: Push changes if they exist
        if: env.changes_exist == 'true'
        run: |
          git push origin HEAD:refs/heads/main
          git push origin HEAD:refs/heads/main --tags

      - name: Create release on new tag if new changes exist
        if: env.changes_exist == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo $TAG_NAME
          gh release create "$TAG_NAME" \
            --title "$TAG_NAME" \
            --notes "See: https://github.com/posit-dev/air/releases/tag/${TAG_NAME}" \
            --latest
